version: "3.7"

services:
  app:
    image: ttlpta-html-nginx:latest
    volumes:
      - .:/usr/share/nginx/html # this is for take effect in docker container when changing code
    ports:
      - "3001:80"
    restart: unless-stopped

# docker compose up -d